frontend-origin: ${frontend-origin}

service:
  lecture:
    host: ${lecture-host}
    port: ${lecture-port}
  auth:
    host: ${auth-host}
    port: ${auth-port}
  notibot:
    host: ${notibot-host}
    port: ${notibot-port}
  gateway:
    host: ${gateway-host}
    port: ${gateway-port}
  payment:
    host: ${payment-host}
    port: ${payment-port}
  rollback:
    host: ${rollback-host}
    port: ${rollback-port}
  verification:
    host: ${verification-host}
    port: ${verification-port}
  ai-curriculum-analysis:
    host: ${ai-curriculum-analysis-host}
    port: ${ai-curriculum-analysis-port}
  ai-chat:
    host: ${ai-chat-host}
    port: ${ai-chat-port}


spring:
  jackson:
    default-property-inclusion: non_null

  messages:
    encoding: UTF-8

  data:
    redis:
      password: ${redis-password}

  datasource:
    username: ${db-username}
    password: ${db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    username: ${rabbit-username}
    password: ${rabbit-password}

  cloud:
    aws:
      credentials:
        access-key: ${aws-access-key}
        secret-key: ${aws-secret-key}
      region:
        static: ap-northeast-2
      s3:
        bucket: aigongbu-default-bucket

webclient:
  portone-uri: https://api.iamport.kr

portone:
  imp-key: ${portone-imp-key}
  imp-secret: ${portone-imp-secret}

jwt:
  issuer: ${jwt-issuer}
  secret_key: ${jwt-secret}

logging:
  level:
    root: INFO
    org.springframework.web: INFO