
spring:
  data:
    redis:
      host: ${redis-host}
      port: 6397
      password: ${redis-password}

  datasource:
    username: ${db-username}
    password: ${db-password}
    url: jdbc:mysql://${db-host}:${db-port}/${db-name}

  rabbitmq:
    username: ${rabbit-username}
    password: ${rabbit-password}
    host: ${rabbit-host}
    port: ${rabbit-port}

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
