
spring:
  profiles:
    active: default

  jackson:
    default-property-inclusion: non_null

  messages:
    encoding: UTF-8

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: aigongbu-default-bucket

springdoc:
  swagger-ui:
    path: /swagger-ui.html

webclient:
  portone-uri: https://api.iamport.kr

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security.web.FilterChainProxy: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    reactor.netty: INFO
    org.springframework.http.server.reactive: INFO
