spring:
  data:
    redis:
      host: localhost
      port: 6397
      password: 12341234

  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3307/data

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 12341234

springdoc:
  swagger-ui:
    path: /swagger-ui.html

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG