server:
  port: 9001

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/user    # 공통의 DB url을 오버라이드
    # username, password, driver-class-name은 공통에서 그대로 상속됨

  data:
    redis:
    # host, port, password는 공통 상속이므로 생략 가능

  servlet:
    multipart:
      max-file-size: 15MB     # 공통 값과 같으면 생략해도 되고,
      max-request-size: 15MB  # 서비스별로 다르면 꼭 명시!

  mail:
  # 공통의 gmail 설정 사용, username/password도 공통에서 가져옴

cloud:
  aws:
    s3:
      bucket: aigongbu-profile-2324    # 이 bucket만 서비스별로 다르면 오버라이드

naver:
  client-id: ${naver-client-id}        # 공통엔 없는 auth만의 설정
  client-secret: ${naver-client-secret}
  redirect-uri: http://localhost:8080/login/oauth2/redirect

jwt:
  issuer: ${jwt-issuer}                # 공통에서 이미 정의돼 있다면 생략해도 됨(같으면)
  secret_key: ${jwt-secret}

badword:
  file-path: word_list.json            # 공통 사용 중이면 생략 가능

mybatis:
  mapper-locations: classpath:mappers/*.xml      # 공통과 같으면 생략, 다르면 명시
  type-aliases-package: com.example.authservice.model

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html