server:
  port: 80

spring:
  application:
    name: auth-service

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    s3:
      bucket: aigongbu-profile-2324

naver:
  redirect-uri: http://localhost:8080/login/oauth2/redirect
  client-id: ${naver-client-id}
  client-secret: ${naver-client-secret}

badword:
  file-path: word_list.json

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html