spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user

  mail:
    username: ${mail-username}
    password: ${mail-password}

naver:
  client-id: ${naver-client-id}
  client-secret: ${naver-client-secret}
