server:
  port: 9001

spring:
  application:
    name: auth-service

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  datasource:
    url: jdbc:mysql://localhost:3307/user
    username: ${db-username}
    password: ${db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: ${redis-password}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      access-key: ${aws-access-key}
      secret-key: ${aws-secret-key}
    region:
      static: ap-northeast-2
    s3:
      bucket: aigongbu-profile-2324

naver:
  client-id: ${naver-client-id}
  client-secret: ${naver-client-secret}
  redirect-uri: http://localhost:8080/login/oauth2/redirect

jwt:
  issuer: ${jwt-issuer}
  secret_key: ${jwt-secret}

badword:
  file-path: word_list.json

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
