server:
  port: 9001

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/user
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

naver:
  redirect-uri: http://localhost:8080/login/oauth2/redirect

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: aigongbu-profile-2324

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

badword:
  file-path: word_list.json

jwt: {}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
