server:
  port: 0  # 의미 없는 기본값

spring:
  application:
    name: auth-service

  datasource:
    url: ""
    username: ""
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ""
      port: 0
      password: ""

  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

naver:
  client-id: ""
  client-secret: ""
  redirect-uri: ""

cloud:
  aws:
    credentials:
      access-key: ""
      secret-key: ""
    region:
      static: ""
    s3:
      bucket: ""

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

badword:
  file-path: word_list.json

jwt:
  issuer: ""
  secret_key: ""

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
