server:
  port: ${AUTH_PORT}

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_AUTH_USERNAME}
    password: ${MAIL_AUTH_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

naver:
  client-id: ${NAVER_AUTH_CLIENT_ID}
  client-secret: ${NAVER_AUTH_CLIENT_SECRET}
  redirect-uri: ${NAVER_AUTH_REDIRECT_URI}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_PROFILE_ACCESS}
      secret-key: ${AWS_S3_PROFILE_SECRET}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_PROFILE_NAME}

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

badword:
  file-path: word_list.json

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
