server:
  port: AUTH_SERVICE_PORT

spring:
  application:
    name: auth-service

  datasource:
    url: AUTH_DATASOURCE_URL
    username: AUTH_MYSQL_NAME
    password: AUTH_MYSQL_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: REDIS_HOST
      port: REDIS_PORT
      password: REDIS_PASSWORD

  mail:
    host: smtp.gmail.com
    port: 587
    username: GMAIL_ID
    password: GMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

naver:
  client-id: NAVER_ID
  client-secret: NAVER_PASSWORD
  redirect-uri: NAVER_REDIRECT

cloud:
  aws:
    credentials:
      access-key: AWS_S3_PROFILE_ACCESS
      secret-key: AWS_S3_PROFILE_SECRET
    region:
      static: AWS_REGIN_STATIC
    s3:
      bucket: AWS_S3_PROFILE_NAME

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

badword:
  file-path: word_list.json

jwt:
  issuer: JWT_ISSUER
  secret_key: JWT_SECRET_KEY

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
