server:
  port: 9001

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/user    # 공통의 DB url을 오버라이드

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    s3:
      bucket: aigongbu-profile-2324

naver:
  client-id: ${naver-client-id}
  client-secret: ${naver-client-secret}
  redirect-uri: http://localhost:8080/login/oauth2/redirect

jwt:
  issuer: ${jwt-issuer}                # 공통에서 이미 정의돼 있다면 생략해도 됨(같으면)
  secret_key: ${jwt-secret}

badword:
  file-path: word_list.json

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html