server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        # CORS 세부 설정은 각 환경 프로파일에서 오버라이드
        cors-configurations: {}

      httpclient:
        connect-timeout: 5000
        response-timeout: 180s

      routes: []
      # 라우트는 기본엔 비워두고 환경별 yml에서 덮어쓴다

resilience4j:
  circuitbreaker:
    configs:
      default:
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000

  timelimiter:
    configs:
      default:
        timeoutDuration: 180s

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
    com.example.gatewayservice: INFO
    reactor.netty: INFO
    org.springframework.http.server.reactive: INFO

team:
  auth-service-url: "" # 환경별로 오버라이드
