server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:8080"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      httpclient:
        connect-timeout: 5000
        response-timeout: 180s

      routes:
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auths/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: payment-service
          uri: http://localhost:9002
          predicates:
            - Path=/pay/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: lecture-service
          uri: http://localhost:9004
          predicates:
            - Path=/lectures/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: notibot-service
          uri: http://localhost:9006
          predicates:
            - Path=/noti/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: ai-curriculum-analysis-server
          uri: http://localhost:8000
          predicates:
            - Path=/ai/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: ai-code-helper
          uri: http://localhost:8001
          predicates:
            - Path=/ai/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # Increased for AI service
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: aiCircuitBreaker
                fallbackUri: forward:/fallback/static

              # WebSocket route for AI chat - ensure this comes before the regular aichat route
        - id: ai-chat-websocket
          uri: ws://localhost:8001
          predicates:
            - Path=/aichat/websocket
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@smartKeyResolver}"

        - id: ai-chat
          uri: http://localhost:8001
          predicates:
            - Path=/aichat/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # Increased for AI chat
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: aiChatCircuitBreaker
                fallbackUri: forward:/fallback/static

team:
  auth-service-url: http://localhost:9001
