server:
  port: 80

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:8080"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      httpclient:
        connect-timeout: 5000
        response-timeout: 180s

      routes:
        - id: auth-service
          predicates:
            - Path=/auths/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: payment-service
          predicates:
            - Path=/pay/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: lecture-service
          predicates:
            - Path=/lectures/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: notibot-service
          predicates:
            - Path=/noti/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: ai-curriculum-analysis-service
          predicates:
            - Path=/ai/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/static

        - id: ai-chat-websocket
          predicates:
            - Path=/aichat/websocket

        - id: ai-chat
          uri: http://localhost:8001
          predicates:
            - Path=/aichat/**
          filters:
            - name: PreGatewayFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@smartKeyResolver}"
            - name: CircuitBreaker
              args:
                name: aiWebSocketCircuitBreaker
                fallbackUri: forward:/fallback/static

resilience4j:
  circuitbreaker:
    configs:
      default:
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000

  timelimiter:
    configs:
      default:
        timeoutDuration: 180s

team:
  auth-service-url: http://localhost:9001

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    com.example.gatewayservice: DEBUG
    reactor.netty: DEBUG
    org.springframework.http.server.reactive: DEBUG