server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:8080"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      httpclient:
        connect-timeout: 5000
        response-timeout: 180s

      routes:
        - id: auth-service
          uri: http://localhost:9001

        - id: payment-service
          uri: http://localhost:9002

        - id: lecture-service
          uri: http://localhost:9004

        - id: notibot-service
          uri: http://localhost:9006

        - id: ai-curriculum-analysis-service
          uri: http://localhost:8000

        - id: ai-chat-websocket
          uri: ws://localhost:8001

        - id: ai-chat
          uri: http://localhost:8001

team:
  auth-service-url: http://localhost:9001
