server:
  port: 80

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "${frontend-origin}"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      httpclient:
        connect-timeout: 5000
        response-timeout: 180s


team:
  auth-service-url: http://${auth-host}:${auth-port}
