server:
  port: 9004

spring:
  application:
    name: lecture-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 250MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3307/lecture?useUnicode=true&characterEncoding=utf8
    username: ${db-username}
    password: ${db-password}

cloud:
  aws:
    credentials:
      access-key: ${aws-access-key}
      secret-key: ${aws-secret-key}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: aigongbu-lecture-files

file:
  upload-dir: "C:/upload_files"

team:
  auth-service-url: http://localhost:9001

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
