server:
  port: 9004

spring:
  application:
    name: lecture-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB    # 공통(15MB)보다 크면 오버라이드!
      max-request-size: 250MB # 공통(15MB)보다 크면 오버라이드!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3307/lecture?useUnicode=true&characterEncoding=utf8

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: aigongbu-lecture-files   # 공통과 다를 때만 명시

file:
  upload-dir: "C:/upload_files"

team:
  auth-service-url: http://localhost:9001

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
