server:
  port: 80

spring:
  application:
    name: lecture-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: aigongbu-lecture-files

team:
  auth-service-url: http://auth-service:80