server:
  port: 9004

spring:
  application:
    name: lecture-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3307/default

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: aigongbu-default-bucket

file:
  upload-dir: /tmp/uploads                     # 기본 템플릿, 환경마다 override

team:
  auth-service-url: ""

logging:
  level:
    org.springframework.cloud.vault: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
