server:
  port: 9006

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/notitable

team:
  auth-service-url: http://localhost:9001

logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring.SqlSessionFactoryBean: DEBUG
