server:
  port: 9002

spring:
  application:
    name: payment-service

  r2dbc:
    url: r2dbc:mysql://localhost:3307/order
    username: root
    password: 12341234

webclient:
  lecture-uri: http://localhost:9004