server:
  port: 9002

spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:mysql://localhost:3307/order
    username: ${db-username}
    password: ${db-password}
  cloud:
    function:
      definition: verified;rollBacked
    stream:
      bindings:
        verified-in-0:
          destination: verify-response
          group: ${spring.application.name}
        rollBacked-in-0:
          destination: rollback-response
          group: ${spring.application.name}
        verify-out-0:
          destination: verify-request
        rollback-out-0:
          destination: rollback-request
      rabbit:
        bindings:
          verify-out-0:
            producer:
              transacted: true
          rollback-out-0:
            producer:
              transacted: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbit-username}
    password: ${rabbit-password}

webclient:
  portone-uri: https://api.iamport.kr
  lecture-uri: http://localhost:9004

portone:
  imp-key: ${portone-imp-key}
  imp-secret: ${portone-imp-secret}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
