server:
  port: 9007

spring:
  application:
    name: rollback-service
  cloud:
    function:
      definition: rollback
    stream:
      bindings:
        rollback-in-0:
          destination: rollback-request
          group: ${spring.application.name}
        rollback-out-0:
          destination: rollback-response
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbit-username}
    password: ${rabbit-password}

webclient:
  portone-uri: https://api.iamport.kr

portone:
  imp-key: ${portone-imp-key}
  imp-secret: ${portone-imp-secret}
