server:
  port: ${ROLLBACK_SERVICE_PORT}

spring:
  application:
    name: rollback-service

  cloud:
    function:
      definition: rollback
    stream:
      bindings:
        rollback-in-0:
          destination: rollback-request
          group: ${spring.application.name}
        rollback-out-0:
          destination: rollback-response

  rabbitmq:
    host: ${ROLLBACK_RABBITMQ_HOST}
    port: ${ROLLBACK_RABBITMQ_PORT}
    username: ${ROLLBACK_RABBITMQ_NAME}
    password: ${ROLLBACK_RABBITMQ_PASSWORD}

webclient:
  portone-uri: ${PORTONE_URL}

portone:
  imp-key: ${PORTONE_KEY}
  imp-secret: ${PORTONE_SECRET}
