server:
  port: 9003

spring:
  application:
    name: verification-service
  cloud:
    function:
      definition: verify
    stream:
      bindings:
        verify-in-0:
          destination: verify-request
          group: ${spring.application.name}
        verify-out-0:
          destination: verify-response
  rabbitmq:
    host: localhost
    port: 5672
    username: ${rabbit-username}
    password: ${rabbit-password}

webclient:
  portone-uri: https://api.iamport.kr

portone:
  imp-key: ${portone-imp-key}
  imp-secret: ${portone-imp-secret}
