server:
  port: 9003
spring:
  application:
    name: verification-service
  cloud:
    function:
      definition: verify
    stream:
      bindings:
        verify-in-0:
          destination: verify-request
          group: ${spring.application.name}
        verify-out-0:
          destination: verify-response