server:
  port: 9001

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/user}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:12341234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:12341234}
  mail:
    host: smtp.gmail.com
    port: 587
    username: dudwls326@gmail.com
    password: pbhc kksk kfil xqie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

naver:
  client-id: avCowJdnr6vGSMChndkD
  client-secret: i99wAdqTLW
  redirect-uri: http://localhost:8080/login/oauth2/redirect

  #          kakao:
  #            client-id: YOUR_KAKAO_CLIENT_ID
  #            client-secret: YOUR_KAKAO_CLIENT_SECRET
  #            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
  #            scope:
  #              - profile_nickname
  #              - account_email

cloud:
  aws:
    credentials:
      access-key: AKIA4ZPZVM5RUE3VX4PR
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: aigongbu-profile-2324

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

badword:
  file-path: word_list.json

jwt:
  issuer: yjincode@naver.com
  secret_key: TxtJis9h77eIpfHsfMdvUqivAE58iDFgMkCnGZL/BlADgUzv1gfox6224u4Rwg+7VhwNeolG5PJiN3vggm1Pzw==

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
